
version: '3.4'

services:

  # elasticsearch:
  #  container_name: elasticsearch
  #  build: ./deploy/elk/elasticsearch/
  #  image: tunnm/docker-es-cococ-tokenizer:7.12.1
  #  volumes:
  #    - ./deploy/elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  #  ports:
  #    - "9200:9200"
  #    - "9300:9300"
  #  environment:
  #    ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
   container_name: logstash
   restart: on-failure
   build:
     context: deploy/elk/logstash/
   volumes:
     - ./deploy/elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
     - ./deploy/elk/logstash/pipeline:/usr/share/logstash/pipeline:ro
   ports:
     - "8686:8080"
    #  - 5044:5044
    #  - 50000:50000/tcp
    #  - 50000:50000/udp
    #  - 9600:9600
   environment:
     LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    restart: on-failure
    image: docker.elastic.co/kibana/kibana:8.7.0
    environment:
      ELASTICSEARCH_HOSTS: http://192.168.3.162:9201
      ELASTICSEARCH_PASSWORD: "changeme"
      ELASTICSEARCH_SERVICEACCOUNTTOKEN: "AAEAAWVsYXN0aWMva2liYW5hL3Rva2VuMTo0QlhVVFAyV1R2eXUzNV9ub05UcDNn"
      server.name: kibana
      server.host: 0.0.0.0
      elasticsearch.hosts: http://192.168.3.162:9201
      ELASTICSEARCH_URL: http://192.168.3.162:9201
      KIBANA_SYSTEM_PASSWORD: "abc@123"
      xpack.security.encryptionKey: "4JhT9pWqU5Oz7yXmRvF1AeB6lP8dK2cN"
    mem_limit: 1294967296
    volumes:
      - ./deploy/elk/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - 5601:5601
    networks:
      - elastic
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status

  apm-server:
    restart: on-failure
    image: docker.elastic.co/apm/apm-server:8.7.0
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    ports:
      - 8200:8200
    command: >
       apm-server -e
         -E apm-server.rum.enabled=true
         -E setup.kibana.host=kibana:5601
         -E setup.template.settings.index.number_of_replicas=0
         -E apm-server.kibana.enabled=true
         -E apm-server.kibana.host=kibana:5601
         -E output.elasticsearch.username=elastic
         -E output.elasticsearch.password=changeme
         -E output.elasticsearch.hosts=["192.168.3.162:9201"]
    mem_limit: 1g
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/
    networks:
    - elastic
  
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.7.0
    restart: on-failure
    hostname: "{{.Node.Hostname}}-metricbeat"
    user: root
    networks:
      - elastic
    # configs:
    #   - source: mb_config
    #     target: /usr/share/metricbeat/metricbeat.yml
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - metricbeat:/usr/share/metricbeat/data
    environment:
      - ELASTICSEARCH_HOST=http://192.168.3.162:9201
      - KIBANA_HOST=http://localhost:5601
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    # disable strict permission checks
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    deploy:
      mode: global


volumes:
  metricbeat:
networks:
 elastic:
   driver: bridge
        